# 检查metadata中数据信息

In [2]:
import numpy as np

australian_metadata = np.load('./australian_metadata.npy')
print(np.shape(australian_metadata))
process_australian_metadata = np.load('./process_australian_metadata.npy')
process_classify_australian_metadata = np.load('./process_classify_australian_metadata.npy')

(259200, 400)


## (1)样本本身的信息 （共35维）
1. 数据集特征维度（属性维度）[0]
2. 已标记的数据集中正样本的比例，负样本的比例 [1, 2]
3. 根据当前模型的预测值，计算未标记数据集中，模型预测为正样本的比例，负样本的比例 [3, 4]

In [12]:
# print(australian_metadata[0:5, 0:5])
# print(australian_metadata[0:5, 396])
print(process_australian_metadata[0:5, 0:5])
print(process_australian_metadata[0:5, 396])

[[4.20000000e+01 3.75000000e-01 6.25000000e-01 7.43494424e-03
  9.92565056e-01]
 [4.20000000e+01 3.75000000e-01 6.25000000e-01 6.31970260e-02
  9.36802974e-01]
 [4.20000000e+01 3.75000000e-01 6.25000000e-01 1.11524164e-02
  9.88847584e-01]
 [4.20000000e+01 3.75000000e-01 6.25000000e-01 7.43494424e-03
  9.92565056e-01]
 [4.20000000e+01 3.75000000e-01 6.25000000e-01 4.08921933e-02
  9.59107807e-01]]
[0.01210654 0.05326877 0.02421308 0.01452785 0.03874092]


1. 在整个数据集（包含已标记和未标记）中进行聚类，获取10个聚类中心点， [5, 15]

并按照每个中心点与x的距离从小到大排序记为 a_i  ⅈ=1,2,……10 (这10个点的顺序是根据不同的x变化的)。

计算x与上述10个代表性样本数据点的欧氏距离，并做归一化处理：

(|(|x-a_i |)|^2-min⁡{|(|x_j-a_i |)|^2})/(max⁡{|(|x_j-a_i |)|^2}-min⁡{|(|x_j-a_i |)|^2}⁡). 

其中x_j是在整个数据集范围内的。



2. 按照当前模型对已标记数据集的预测值进行排序，选出10等分点的数据 b_i  ⅈ=1,2,……10。 [15, 25]

计算x与上述10个代表性样本数据点的欧氏距离，并做归一化处理：

(|(|x-b_i |)|^2-min⁡{|(|x_j-b_i |)|^2})/(max⁡{|(|x_j-b_i |)|^2}-min⁡{|(|x_j-b_i |)|^2}⁡). 

其中x_j是在整个数据集范围内的。



3. 按照当前模型对未标记数据集的预测值进行排序，选出10等分点的数据 c_i  ⅈ=1,2,……10。 [25, 35]

计算x与上述10个代表性样本数据点的欧氏距离，并做归一化处理：

(|(|x-c_i |)|^2-min⁡{|(|x_j-c_i |)|^2})/(max⁡{|(|x_j-c_i |)|^2}-min⁡{|(|x_j-c_i |)|^2}⁡). 

其中x_j是在整个数据集范围内的。

In [16]:
print('*****a_i \n')
print(process_australian_metadata[0:5, 5:15])
print('*****b_i \n')
print(process_australian_metadata[0:5, 15:25])
print('*****c_i \n')
print(process_australian_metadata[0:5, 25:35])

# print(process_australian_metadata[0:5, 396])

*****a_i 

[[0.         0.53289573 0.54093969 0.62868811 0.64592502 0.73820874
  0.74398245 0.91998283 0.92333148 1.        ]
 [0.         0.1659716  0.31733797 0.57085108 0.57191929 0.68785242
  0.79622707 0.79816479 0.89846172 1.        ]
 [0.         0.46757069 0.68851514 0.69147759 0.77243081 0.77617344
  0.85513864 0.86452799 0.92964971 1.        ]
 [0.         0.17949803 0.31678593 0.44954155 0.57374141 0.5807421
  0.58307313 0.89822161 0.99431673 1.        ]
 [0.         0.23020473 0.23126962 0.23454198 0.44152425 0.63791698
  0.82984899 0.99306036 0.99371007 1.        ]]
*****b_i 

[[0.78716828 0.78716828 0.74440153 0.78797847 0.75433806 0.6342238
  0.6342238  0.         1.         0.8412521 ]
 [0.80263141 0.80263141 0.75675014 1.         0.80096188 0.87161282
  0.87161282 0.66107728 0.         0.65715962]
 [0.8169689  0.8169689  0.91855308 0.99808675 0.57972567 0.66508798
  0.66508798 0.         1.         0.99872776]
 [0.71106707 0.71106707 0.66057803 0.60493319 0.68550477 0.

## (2)模型本身的信息，（共180维）

1)	在已标记数据上计算TP、FP、TN、FN的比例 (分别为连续的6个值）

In [40]:
print('第一轮的  \n',process_australian_metadata[0:10, [35, 41, 47, 53]])
print('第二轮的  \n',process_australian_metadata[0:10, [36, 42, 48, 54]])
print('第三轮的  \n',process_australian_metadata[0:10, [37, 43, 49, 55]])
print('第四轮的  \n',process_australian_metadata[0:10, [38, 44, 50, 56]])
print('第五轮的  \n',process_australian_metadata[0:10, [39, 45, 51, 57]])
print('第六轮的  \n',process_australian_metadata[0:10, [40, 46, 52, 58]])

第一轮的  
 [[0.         0.         0.66666667 0.33333333]
 [0.         0.         0.66666667 0.33333333]
 [0.         0.         0.66666667 0.33333333]
 [0.         0.         0.66666667 0.33333333]
 [0.         0.         0.66666667 0.33333333]
 [0.66666667 0.33333333 0.         0.        ]
 [0.66666667 0.33333333 0.         0.        ]
 [0.66666667 0.33333333 0.         0.        ]
 [0.66666667 0.33333333 0.         0.        ]
 [0.66666667 0.33333333 0.         0.        ]]
第二轮的  
 [[0.   0.   0.75 0.25]
 [0.   0.   0.75 0.25]
 [0.   0.   0.75 0.25]
 [0.   0.   0.75 0.25]
 [0.   0.   0.75 0.25]
 [0.5  0.   0.5  0.  ]
 [0.5  0.   0.5  0.  ]
 [0.5  0.   0.5  0.  ]
 [0.5  0.   0.5  0.  ]
 [0.5  0.   0.5  0.  ]]
第三轮的  
 [[0.  0.  0.8 0.2]
 [0.  0.  0.8 0.2]
 [0.  0.  0.8 0.2]
 [0.  0.  0.8 0.2]
 [0.  0.  0.8 0.2]
 [0.2 0.  0.6 0.2]
 [0.2 0.  0.6 0.2]
 [0.2 0.  0.6 0.2]
 [0.2 0.  0.6 0.2]
 [0.2 0.  0.6 0.2]]
第四轮的  
 [[0.         0.         0.66666667 0.33333333]
 [0.         0.         0.66

2) 在已标记数据上按照当前模型对已标记数据集的预测值做归一化处理（在整个数据集上选出最小最大值进行归一化），并进行排序，选出10等分点的值记录

In [33]:
print('第一轮的  \n',process_australian_metadata[0:10, 59:69])
print('第二轮的  \n',process_australian_metadata[0:10, 69:79])
print('第三轮的  \n',process_australian_metadata[0:10, 79:89])
print('第四轮的  \n',process_australian_metadata[0:10, 89:99])
print('第五轮的  \n',process_australian_metadata[0:10, 99:109])
print('第六轮的  \n',process_australian_metadata[0:10, 109:119])

第一轮的  
 [[0.         0.         0.         0.         0.00420065 0.00420065
  0.00420065 1.         1.         1.        ]
 [0.         0.         0.         0.         0.00420065 0.00420065
  0.00420065 1.         1.         1.        ]
 [0.         0.         0.         0.         0.00420065 0.00420065
  0.00420065 1.         1.         1.        ]
 [0.         0.         0.         0.         0.00420065 0.00420065
  0.00420065 1.         1.         1.        ]
 [0.         0.         0.         0.         0.00420065 0.00420065
  0.00420065 1.         1.         1.        ]
 [0.         0.         0.         0.         0.46766087 0.46766087
  0.46766087 1.         1.         1.        ]
 [0.         0.         0.         0.         0.46766087 0.46766087
  0.46766087 1.         1.         1.        ]
 [0.         0.         0.         0.         0.46766087 0.46766087
  0.46766087 1.         1.         1.        ]
 [0.         0.         0.         0.         0.46766087 0.46766087
  0.

3) 计算2)中10个值（归一化后）的均值和方差 [119, 120]

In [39]:
print('第一轮的  \n',process_australian_metadata[0:10, [119, 125]])
print('第二轮的  \n',process_australian_metadata[0:10, [120, 126]])
print('第三轮的  \n',process_australian_metadata[0:10, [121, 127]])
print('第四轮的  \n',process_australian_metadata[0:10, [122, 128]])
print('第五轮的  \n',process_australian_metadata[0:10, [123, 129]])
print('第六轮的  \n',process_australian_metadata[0:10, [124, 130]])

第一轮的  
 [[0.30126019 0.45743589]
 [0.30126019 0.45743589]
 [0.30126019 0.45743589]
 [0.30126019 0.45743589]
 [0.30126019 0.45743589]
 [0.44029826 0.41442665]
 [0.44029826 0.41442665]
 [0.44029826 0.41442665]
 [0.44029826 0.41442665]
 [0.44029826 0.41442665]]
第二轮的  
 [[0.23965112 0.3839981 ]
 [0.23965112 0.3839981 ]
 [0.23965112 0.3839981 ]
 [0.23965112 0.3839981 ]
 [0.23965112 0.3839981 ]
 [0.35611261 0.37163838]
 [0.35611261 0.37163838]
 [0.35611261 0.37163838]
 [0.35611261 0.37163838]
 [0.35611261 0.37163838]]
第三轮的  
 [[0.23737136 0.3847945 ]
 [0.23737136 0.3847945 ]
 [0.23737136 0.3847945 ]
 [0.23737136 0.3847945 ]
 [0.23737136 0.3847945 ]
 [0.27918244 0.3836127 ]
 [0.27918244 0.3836127 ]
 [0.27918244 0.3836127 ]
 [0.27918244 0.3836127 ]
 [0.27918244 0.3836127 ]]
第四轮的  
 [[0.341134   0.43062855]
 [0.341134   0.43062855]
 [0.341134   0.43062855]
 [0.341134   0.43062855]
 [0.341134   0.43062855]
 [0.31994572 0.35097437]
 [0.31994572 0.35097437]
 [0.31994572 0.35097437]
 [0.31994572 0.

4) 在未标记数据上，根据当前模型的预测值，计算未标记数据集中，模型预测为正样本的比例，负样本的比例 [131, 142]

In [38]:
print('第一轮的  \n',process_australian_metadata[0:10, [131, 137]])
print('第二轮的  \n',process_australian_metadata[0:10, [132, 138]])
print('第三轮的  \n',process_australian_metadata[0:10, [133, 139]])
print('第四轮的  \n',process_australian_metadata[0:10, [134, 140]])
print('第五轮的  \n',process_australian_metadata[0:10, [135, 141]])
print('第六轮的  \n',process_australian_metadata[0:10, [136, 142]])

第一轮的  
 [[0.00729927 0.99270073]
 [0.06934307 0.93065693]
 [0.01094891 0.98905109]
 [0.00729927 0.99270073]
 [0.04014599 0.95985401]
 [0.61313869 0.38686131]
 [0.6350365  0.3649635 ]
 [0.53284672 0.46715328]
 [0.54379562 0.45620438]
 [0.57664234 0.42335766]]
第二轮的  
 [[0.00732601 0.99267399]
 [0.06959707 0.93040293]
 [0.01098901 0.98901099]
 [0.00732601 0.99267399]
 [0.04029304 0.95970696]
 [0.61538462 0.38461538]
 [0.63736264 0.36263736]
 [0.53479853 0.46520147]
 [0.54578755 0.45421245]
 [0.57875458 0.42124542]]
第三轮的  
 [[0.00735294 0.99264706]
 [0.06985294 0.93014706]
 [0.01102941 0.98897059]
 [0.00735294 0.99264706]
 [0.04044118 0.95955882]
 [0.61764706 0.38235294]
 [0.63970588 0.36029412]
 [0.53676471 0.46323529]
 [0.54779412 0.45220588]
 [0.58088235 0.41911765]]
第四轮的  
 [[0.00738007 0.99261993]
 [0.06642066 0.93357934]
 [0.01107011 0.98892989]
 [0.00738007 0.99261993]
 [0.04059041 0.95940959]
 [0.61623616 0.38376384]
 [0.63837638 0.36162362]
 [0.53505535 0.46494465]
 [0.54612546 0.

5) 按照当前模型对未标记数据集的预测值做归一化处理（在整个数据集上选出最小最大值进行归一化），并进行排序，选出10等分点的值记录

In [59]:
print('第一轮的  \n',process_australian_metadata[0:10, 143:153])
print('第一轮的  \n',np.sum(process_australian_metadata[0, 143:153]))

print('第二轮的  \n',process_australian_metadata[0:10, 153:163])
print('第三轮的  \n',process_australian_metadata[0:10, 163:173])
print('第四轮的  \n',process_australian_metadata[0:10, 173:183])
print('第五轮的  \n',process_australian_metadata[0:10, 183:193])
print('第六轮的  \n',process_australian_metadata[0:10, 193:203])

第一轮的  
 [[0.         0.05511888 0.10088094 0.14951968 0.19745633 0.24230169
  0.27144418 0.34317414 0.53353396 0.63384238 0.        ]
 [0.         0.05511888 0.10088094 0.14951968 0.19745633 0.24230169
  0.27144418 0.34317414 0.53353396 0.63384238 0.        ]
 [0.         0.05511888 0.10088094 0.14951968 0.19745633 0.24230169
  0.27144418 0.34317414 0.53353396 0.63384238 0.        ]
 [0.         0.05511888 0.10088094 0.14951968 0.19745633 0.24230169
  0.27144418 0.34317414 0.53353396 0.63384238 0.        ]
 [0.         0.05511888 0.10088094 0.14951968 0.19745633 0.24230169
  0.27144418 0.34317414 0.53353396 0.63384238 0.        ]
 [0.         0.18601717 0.21331902 0.29300535 0.31929071 0.40277054
  0.43217643 0.50496955 0.59108286 0.64846499 0.        ]
 [0.         0.18601717 0.21331902 0.29300535 0.31929071 0.40277054
  0.43217643 0.50496955 0.59108286 0.64846499 0.        ]
 [0.         0.18601717 0.21331902 0.29300535 0.31929071 0.40277054
  0.43217643 0.50496955 0.59108286 0.64846

6)	计算5)中10个值的均值和方差

In [42]:
print('第一轮的  \n',process_australian_metadata[0:10, [203, 209]])
print('第二轮的  \n',process_australian_metadata[0:10, [204, 210]])
print('第三轮的  \n',process_australian_metadata[0:10, [205, 211]])
print('第四轮的  \n',process_australian_metadata[0:10, [206, 212]])
print('第五轮的  \n',process_australian_metadata[0:10, [207, 213]])
print('第六轮的  \n',process_australian_metadata[0:10, [208, 214]])

第一轮的  
 [[0.25272722 0.19298314]
 [0.25272722 0.19298314]
 [0.25272722 0.19298314]
 [0.25272722 0.19298314]
 [0.25272722 0.19298314]
 [0.35910966 0.18766705]
 [0.35910966 0.18766705]
 [0.35910966 0.18766705]
 [0.35910966 0.18766705]
 [0.35910966 0.18766705]]
第二轮的  
 [[0.2688477  0.19811234]
 [0.2688477  0.19811234]
 [0.2688477  0.19811234]
 [0.2688477  0.19811234]
 [0.2688477  0.19811234]
 [0.31814793 0.21517567]
 [0.31814793 0.21517567]
 [0.31814793 0.21517567]
 [0.31814793 0.21517567]
 [0.31814793 0.21517567]]
第三轮的  
 [[0.24217864 0.20028135]
 [0.24217864 0.20028135]
 [0.24217864 0.20028135]
 [0.24217864 0.20028135]
 [0.24217864 0.20028135]
 [0.31535698 0.22043809]
 [0.31535698 0.22043809]
 [0.31535698 0.22043809]
 [0.31535698 0.22043809]
 [0.31535698 0.22043809]]
第四轮的  
 [[0.31658055 0.25953424]
 [0.31658055 0.25953424]
 [0.31658055 0.25953424]
 [0.31658055 0.25953424]
 [0.31658055 0.25953424]
 [0.31331676 0.19860416]
 [0.31331676 0.19860416]
 [0.31331676 0.19860416]
 [0.31331676 0.

7)	将在此轮之前的五轮主动学习过程中，上述1)到6)的特征全部用作本轮的特征

## (3)模型在样本上预测的信息（共181维）

根据当前模型对整个数据集的预测值，做归一化处理

（注意a、b、c三组样本都是本轮选出来的，而不是前5轮选出的）

1) 记录f(x)

In [65]:
print(process_australian_metadata[0:10, 215])

[-0.1797691   0.01190594 -0.19107042 -0.21533045 -0.02637267  0.15412552
  0.13401517  0.09051658  0.24273871  0.16844853]


2)	计算与a，b，c三组共30个样本预测值的差（不是绝对值）。

In [66]:
print('第一轮的  \n a : \n',process_australian_metadata[0:10, 216:226])
print('b:  \n',process_australian_metadata[0:10, 226:236])
print('c:  \n',process_australian_metadata[0:10, 236:246])
# print('第二轮的  \n a : \n',process_australian_metadata[0:10, 246:226])
# print('第二轮的  b:  \n',process_australian_metadata[0:10, 226:236])
# print('第二轮的  c:  \n',process_australian_metadata[0:10, 236:246])
# print('第三轮的  \n a : \n',process_australian_metadata[0:10, 216:226])
# print('第三轮的  b:  \n',process_australian_metadata[0:10, 226:236])
# print('第三轮的  c:  \n',process_australian_metadata[0:10, 236:246])
# print('第四轮的  \n a : \n',process_australian_metadata[0:10, 216:226])
# print('第四轮的  b:  \n',process_australian_metadata[0:10, 226:236])
# print('第四轮的  c:  \n',process_australian_metadata[0:10, 236:246])
# print('第五轮的  \n a : \n',process_australian_metadata[0:10, 216:226])
# print('第五轮的  b:  \n',process_australian_metadata[0:10, 226:236])
# print('第五轮的  c:  \n',process_australian_metadata[0:10, 236:246])
# print('第六轮的  \n a : \n',process_australian_metadata[0:10, 216:226])
# print('第六轮的  b:  \n',process_australian_metadata[0:10, 226:236])
# print('第六轮的  c:  \n',process_australian_metadata[0:10, 236:246])

第一轮的  
 a : 
 [[ 1.79498278e-01  1.34638723e-01  1.33626487e-01 -6.40953724e-03
   3.17801793e-01  3.22606713e-01  3.15415283e-01 -2.59518823e-01
  -5.16916083e-01 -5.72002587e-02]
 [-5.71164372e-02  1.45202127e-01 -3.14513697e-01  3.37041109e-01
   3.36028873e-01  5.20204179e-01  3.81900664e-01  5.17817669e-01
   1.95992849e-01  5.25009099e-01]
 [-3.60440104e-03 -4.61663694e-03 -3.97761947e-01  1.77172159e-01
  -1.44652661e-01  1.79558669e-01  4.12551534e-02  1.84363589e-01
  -1.95443383e-01 -6.55159208e-01]
 [ 1.87920236e-01  1.83115316e-01  1.80728806e-01 -1.41096014e-01
  -4.77538647e-05 -1.05998976e-03  4.48118006e-02 -1.91886736e-01
  -3.94205300e-01 -6.51602560e-01]
 [ 9.52340864e-02 -1.07084478e-01  4.75041058e-01 -3.64481738e-01
   4.70236138e-01  4.67849628e-01  1.46024808e-01  2.87073068e-01
   2.86060832e-01  3.31932623e-01]
 [ 9.37176804e-02  9.34506559e-02  3.86453955e-01  4.70353675e-01
  -1.24540655e-02 -1.22256880e-01  3.60512745e-01  3.75681518e-01
  -3.19520827e-01  

3)	将在此轮之前的五轮主动学习过程中，上述1)到2）的特征全部用作本轮的特征

## 查看metadata的（y）性能提升

In [7]:
improve_accuracy_max = np.max(process_australian_metadata[:, 396])
improve_accuracy_min = np.min(process_australian_metadata[:, 396])
print('improve_accuracy_max:  ', improve_accuracy_max)
print('improve_accuracy_min:  ', improve_accuracy_min)

improve_accuracy_mean = np.mean(process_australian_metadata[:, 396])
improve_accuracy_std = np.std(process_australian_metadata[:, 396])
print('improve_accuracy_mean:  ', improve_accuracy_mean)
print('improve_accuracy_std:  ', improve_accuracy_std)

postive_improve_accuracy_mean = np.mean(process_australian_metadata[np.where(process_australian_metadata[:, 396]>0)[0], 396])
postive_improve_accuracy_std = np.std(process_australian_metadata[np.where(process_australian_metadata[:, 396]>0)[0], 396])
print('postive_improve_accuracy_mean:  ', postive_improve_accuracy_mean)
print('postive_improve_accuracy_std:  ', postive_improve_accuracy_std)

negative_improve_accuracy_mean = np.mean(process_australian_metadata[np.where(process_australian_metadata[:, 396]<0)[0], 396])
negative_improve_accuracy_std = np.std(process_australian_metadata[np.where(process_australian_metadata[:, 396]<0)[0], 396])
print('negative_improve_accuracy_mean:  ', negative_improve_accuracy_mean)
print('negative_improve_accuracy_std:  ', negative_improve_accuracy_std)

improve_accuracy_max:   0.3946731234866829
improve_accuracy_min:   -0.288135593220339
improve_accuracy_mean:   0.0123009177975682
improve_accuracy_std:   0.054105726541675815
postive_improve_accuracy_mean:   0.04630791669561194
postive_improve_accuracy_std:   0.04298588233224687
negative_improve_accuracy_mean:   -0.03316461773753704
negative_improve_accuracy_std:   0.027524423850107123
